name: batopt

channels:
  - conda-forge
  - fastai
  
dependencies:
  - python>=3.7
  - pandas
  - matplotlib
  - jupyterlab
  - seaborn
  - mkdocs
  - mkdocs-material
  - python-dotenv
  - dagster
  - lxml
  - scikit-learn
  - scikit-optimize
  - typer
  - pip
  
  - pip:
      - -e .
      - nbdev
      - moepy
      - ipypb
      - feautils
      - mkdocs-material-extensions
      - mkdocstrings
      - configparser
      - junix