# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"encode_file_as_utf8": "00-utilities.ipynb",
         "convert_nbs_to_md": "00-utilities.ipynb",
         "MyHTMLParser": "00-utilities.ipynb",
         "convert_df_to_md": "00-utilities.ipynb",
         "extract_div_to_md_table": "00-utilities.ipynb",
         "extract_div_to_md_tables": "00-utilities.ipynb",
         "clean_md_file_tables": "00-utilities.ipynb",
         "get_substring_idxs": "00-utilities.ipynb",
         "clean_md_file_img_fps": "00-utilities.ipynb",
         "AxTransformer": "00-utilities.ipynb",
         "set_date_ticks": "00-utilities.ipynb",
         "reindex_df_dt_idx": "01-data-cleaning.ipynb",
         "load_training_dataset": "01-data-cleaning.ipynb",
         "combine_training_datasets": "01-data-cleaning.ipynb",
         "identify_df_dt_entries": "01-data-cleaning.ipynb",
         "construct_df_temp_features": "01-data-cleaning.ipynb",
         "split_X_y_data": "01-data-cleaning.ipynb",
         "generate_kfold_preds": "01-data-cleaning.ipynb",
         "evaluate_models": "01-data-cleaning.ipynb",
         "interpolate_missing_panel_temps": "01-data-cleaning.ipynb",
         "construct_df_irradiance_features": "01-data-cleaning.ipynb",
         "interpolate_missing_site_irradiance": "01-data-cleaning.ipynb",
         "construct_df_power_features": "01-data-cleaning.ipynb",
         "interpolate_missing_site_power": "01-data-cleaning.ipynb",
         "interpolate_missing_weather_solar": "01-data-cleaning.ipynb",
         "construct_df_features": "02-demand-forecast.ipynb",
         "estimate_daily_demand_quantiles": "02-demand-forecast.ipynb",
         "charge_to_capacity": "04-battery-optimisation.ipynb",
         "schedule_is_legal": "04-battery-optimisation.ipynb",
         "B_min": "04-battery-optimisation.ipynb",
         "B_max": "04-battery-optimisation.ipynb",
         "C_min": "04-battery-optimisation.ipynb",
         "C_max": "04-battery-optimisation.ipynb",
         "charge_times": "04-battery-optimisation.ipynb",
         "discharge_times": "04-battery-optimisation.ipynb",
         "no_activity_times": "04-battery-optimisation.ipynb"}

modules = ["utils.py",
           "clean.py",
           "demand.py",
           "pv.py",
           "battery.py",
           "eval.py",
           "pipeline.py"]

doc_url = "https://AyrtonB.github.io/WPD-DS-Challenge/"

git_url = "https://github.com/AyrtonB/WPD-DS-Challenge"

def custom_doc_links(name): return None
