# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04-battery-optimisation.ipynb (unless otherwise specified).

__all__ = ['charge_to_capacity', 'schedule_is_legal', 'B_min', 'B_max', 'C_min', 'C_max', 'charge_times',
           'discharge_times', 'no_activity_times']

# Cell
import numpy as np
import pandas as pd

# Cell
def charge_to_capacity(charge_schedule, init_value=0):
    capacity = np.append(np.array([init_value]), np.cumsum(charge_schedule[:-1]/2))
    return capacity

# Cell
B_min = -2.5 # Min rate of charging
B_max = 2.5 # Max rate of charging
C_min = 0. # Min capacity
C_max = 6. # Max capacity
charge_times = ('00:00', '15:00')
discharge_times = ('15:30', '20:30')
no_activity_times = ('21:00', '23:30')

def schedule_is_legal(schedule, B_min=B_min, B_max=B_max, C_min=C_min, C_max=C_max,
                      charge_times=charge_times, discharge_times=discharge_times,
                      no_acivity_times=no_activity_times):
    """
    Determine if a battery schedule meets constraints
    """

    charge = schedule.charge_MW.values
    capacity = charge_to_capacity(schedule.charge_MW.values)
    schedule['capacity'] = capacity
    schedule = schedule.set_index(pd.to_datetime(schedule.datetime))

    if not np.all((charge >= B_min) & (charge <= B_max)): # charge constraints
        return False
    elif not np.all((capacity >= C_min) & (capacity <= C_max)): # capacity constraints
        return False
    elif np.any(schedule.between_time(discharge_times[0], discharge_times[1]).charge_MW.values > 0): # Discharge between discharge_times
        return False
    elif np.any(schedule.between_time(charge_times[0], charge_times[1]).charge_MW.values < 0): # Charge between charge_times
        return False
    elif np.any(schedule.between_time(no_activity_times[0], no_activity_times[1]).charge_MW.values != 0): # No activity between no_activity_times
        return False
    elif np.any(schedule.between_time('00:00', '00:00').capacity.values != 0): # Must be empty at 00:00
        return False
    else:
        return True
