# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09-christmas.ipynb (unless otherwise specified).

__all__ = ['apply_datetime_index']

# Cell
import numpy as np
import pandas as pd

import os
from sklearn.ensemble import RandomForestRegressor

from batopt import clean, discharge, charge, constraints, pv

# Cell
def apply_datetime_index(df):
    df.index = pd.to_datetime(df.index)
    return df