# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08-christmas.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import pandas as pd

import os
from sklearn.ensemble import RandomForestRegressor

from batopt import clean, discharge, charge, constraints, pv