# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/11-covid.ipynb (unless otherwise specified).

__all__ = []

# Cell
import json
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from skopt.plots import plot_objective
from skopt.space import Real, Categorical, Integer

from batopt import clean, discharge, charge, pv, utils, tuning

import os
from ipypb import track