# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06-pipeline.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import pandas as pd

from dagster import execute_pipeline, pipeline, solid, Field

from batopt import clean