# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08-similar-days.ipynb (unless otherwise specified).

__all__ = []

# Cell
import numpy as np
import pandas as pd

from sklearn.cluster import AgglomerativeClustering

from batopt import clean, discharge, charge